const path = require("path");
const MiniCssExtractPlugin = require("mini-css-extract-plugin");
const OptimizeCssAssetsPlugin = require("optimize-css-assets-webpack-plugin");
const FixStyleOnlyEntriesPlugin = require("webpack-fix-style-only-entries"); //remove autogenerated js files
const loader = require("sass-loader");

module.exports = {
  entry: {
    "css-loaders-lib-full": "./src/sass/css-loaders-lib-full.scss",
    "square-wheel": "./src/sass/square-wheel.scss",
    pokem: "./src/sass/pokem.scss",
    pacm: "./src/sass/pacm.scss",
    twins: "./src/sass/twins.scss",
    look: "./src/sass/look.scss",
    nuclear: "./src/sass/nuclear.scss",
  },
  optimization: {
    minimizer: [
      new OptimizeCssAssetsPlugin({
        cssProcessorOptions: { map: { inline: false } },
      }),
    ],
  },
  module: {
    rules: [
      {
        test: /\.scss$/,
        enforce: "pre",
        use: [
          MiniCssExtractPlugin.loader, //4. Extract css into files
          "css-loader", //3 Turns css into javascript
          {
            loader: "postcss-loader", //2. Runs Autoprefixer
            options: {
              ident: "postcss",
              plugins: [require("autoprefixer")],
            },
          },
          "sass-loader", //1. Turns sass into css
        ],
      },
    ],
  },
  plugins: [new FixStyleOnlyEntriesPlugin()],
  devtool: "source-map",
  stats: {
    colors: true,
  },
};
